repos:
  - repo: https://github.com/jmreicha/pre-commit-c7n.git
    rev: 29fa5acb10e8aff88d9da6c3f9dbeaf5ae8ddec5
    hooks:
      - id: c7n-validate
        args:
          - --strict
          - --verbose
          - ./policies # last arg indicates the path/file to validate

  - repo: https://github.com/jmreicha/pre-commit-c7n.git
    rev: v0.1.0
    hooks:
      - id: c7n-validate-docker
        args:
          - --strict
          - --verbose
          - ./policies # last arg indicates the path/file to validate
