- id: c7n-validate
  name: c7n-validate
  description: Validates all Cloud Custodian policy files.
  entry: hooks/c7n-validate.sh
  language: system
  files: policies/.*\.y?ml$

- id: c7n-validate-docker
  name: c7n-validate-docker
  description: Validates all Cloud Custodian policy files using a Docker container.
  entry: cloudcustodian/c7n:0.9.38.0
  language: docker_image
  pass_files: false
