- id: c7n-validate
  name: c7n-validate
  entry: hooks/c7n-validate.sh
  language: system
  files: policies/.*\.y?ml$

- id: c7n-validate-docker
  name: c7n-validate-docker
  entry: cloudcustodian/c7n:0.9.38.0
  language: docker_image
  pass_files: false

# Example
# - id: terragrunt_validate
#   name: Terragrunt validate
#   description: Validates all Terragrunt configuration files.
#   entry: hooks/terragrunt_validate.sh
#   language: script
#   files: (\.hcl)$
#   exclude: \.terraform/.*$
